### ISSUE TITLE
Getting the following error message mapping values are not allowed here in "/config/_config/switches/lockuser_accounts_to_be_managed.yaml", line 2, column 12

### ISSUE THREAD

**Issue by ImaBadCoder** [permissionBRICK/home-assistant-block-user-switch#1]
I am wanting to disable and enable local HA accounts via automation and believe this might be the way to do that. I am getting a message that I shouldn't be mapping values in the yaml.

my yaml looks like this. Notice it is in a sub folder and I am importing everything in that subfolder via an Include statement in the configuration.yaml

- platform: lockuser
    devices:
      useraccount1:
        name: AUser Account 1
        unique_id: 3892900281b9429e9d38f28a88e4b899
      useraccount2:
        name: User Account 2
        unique_id: bff121ede3d044df9990126d3089b38d

Any suggestions as to what I am doing wrong?

**Comment by permissionBRICK** [comment]
Hard to tell because Github ate your whitespaces, could you repost your config as "code" or as an attachment?

**Comment by ImaBadCoder** [comment]
I am to a different spot now. After implementing, I get this in the main log.

`Logger: homeassistant.components.switch
Source: custom_components/lockuser/switch.py:37
Integration: Switch ([documentation](https://www.home-assistant.io/integrations/switch), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+switch%22))
First occurred: 6:00:41 PM (1 occurrences)
Last logged: 6:00:41 PM

Error while setting up lockuser platform for switch
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 281, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/lockuser/switch.py", line 37, in async_setup_platform
    switches.append(CustSwitch(name, device_id, hass, uid, user.is_active))
AttributeError: 'NoneType' object has no attribute 'is_active'`

Thanks for your help.

**Comment by permissionBRICK** [comment]
here is another example for correct formatting:
![image](https://user-images.githubusercontent.com/40219477/213865788-99780ddd-f261-4e12-b757-654943803756.png)
Make sure you use the actual user unique id from the people -> users -> (user)
the name and unique_id must be one indent down from the entity name (in your case Account1:, which is one indent down from devices:
Here is an example:
```
  - platform: lockuser
    devices:
      useraccount1:
        name: AUser Account 1
        unique_id: 3892900281b9429e9d38f28a88e4b899
    devices:
      useraccount2:
        name: User Account 2
        unique_id: bff121ede3d044df9990126d3089b38d
```

**Comment by ImaBadCoder** [comment]
I appreciate the help. Walked away for a bit and decided to come back and troubleshoot the issue. Nothing to troubleshoot as it works exactly as expected.

Thanks again for putting this together.
