### ISSUE TITLE
Deprecated hass.helpers.discovery

### ISSUE THREAD

**Issue by ajstack22** [permissionBRICK/home-assistant-block-user-switch#2]
I'm seeing this message in the Home Assistant log:

Detected that custom integration 'lockuser' accesses hass.helpers.discovery. This is deprecated and will stop working in Home Assistant 2024.11, it should be updated to import functions used from discovery directly at custom_components/lockuser/__init__.py, line 8: hass.helpers.discovery.load_platform('switch', DOMAIN, {}, config), please report it to the author of the 'lockuser' custom integration

Not sure how hard or possible the update would be, but this is a key component to my simplified "Guest Access" configuration and I'd hate to see it go away.

**Comment by permissionBRICK** [comment]
Update pushed to the repo. Replace your __init__.py with the new version

**Comment by permissionBRICK** [comment]
Let me know if it works for you, I didn't expect anyone to actually be using this thing :)

**Comment by ajstack22** [comment]
It appears to be working and I don't see the message in the log anymore, thanks!

I'll take a little bit of time to tell you how I'm using it since I know that it is different than what you initially created it for.  Essentially I wanted a way to be able to enable/disable users programmatically so someone wouldn't have to dig through settings just to give someone access temporarily, say for a guest.  But, theoretically, you could use it to also grant access temporarily to service people for instance.  Our cleaning service can open the smart lock on Tuesdays between 8am and 5pm for instance.  Then just build out the dashboard for them with only what they need and there you go, time-based access because once you disable it it kills their session and their credentials no longer work. I actually built a dashboard to manage the users (as well as their access to given rooms).  Anyway, thanks again!!!

![image](https://github.com/user-attachments/assets/0b0391b3-9661-4c33-8f9f-98421fc0dc4a)

**Comment by permissionBRICK** [comment]
Cool stuff!
